import type { Track } from "./model";

export const SAMPLE_TRACKS: Track[] = [
  {
    id: "1",
    title: "Divinity",
    artist: "Porter Robinson",
    bpm: 90,
    genre: "House",
    energy: 3,
    camelotKey: "10B",
  },
  {
    id: "2",
    title: "Latch",
    artist: "Disclosure",
    bpm: 122,
    genre: "House",
    energy: 2,
    camelotKey: "3B",
  },
  {
    id: "3",
    title: "RATATA",
    artist: "Skrillex",
    bpm: 124,
    genre: "Bass House",
    energy: 3,
    camelotKey: "11B",
  },
  {
    id: "4",
    title: "One Chance",
    artist: "Knock2",
    bpm: 95,
    genre: "Bass House",
    energy: 4,
    camelotKey: "9B",
  },
  {
    id: "5",
    title: "Outer Space",
    artist: "Habstrakt",
    bpm: 126,
    genre: "Bass House",
    energy: 3,
    camelotKey: "1A",
  },
  {
    id: "6",
    title: "Aarena (Knock2 Remix)",
    artist: "ISOxo",
    bpm: 126,
    genre: "Bass House",
    energy: 4,
    camelotKey: "12B",
  },
  {
    id: "7",
    title: "murdah",
    artist: "Knock2",
    bpm: 145,
    genre: "Trap",
    energy: 4,
    camelotKey: "10B",
  },
  {
    id: "8",
    title: "Heads Will Roll (A-Trak Remix)",
    artist: "Yeah Yeah Yeahs",
    bpm: 132,
    genre: "House",
    energy: 4,
    camelotKey: "12A",
  },
  {
    id: "9",
    title: "Clarity",
    artist: "Zedd, Foxes",
    bpm: 128,
    genre: "House",
    energy: 3,
    camelotKey: "4B",
  },
  {
    id: "10",
    title: "LIKE THIS",
    artist: "Atura",
    bpm: 142,
    genre: "House",
    energy: 3,
    camelotKey: "3B",
  },
];
